version: "3.8"
services:
  doscrawler1:
    container_name: doscrawler1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - doscrawler-data:/data/
    logging:
      driver: "json-file"
      options:
        max-size: "5mb"
        max-file: "10"
    depends_on:
      - kafka
      - zookeeper
    environment:
      - SIMPLE_SETTINGS=doscrawler.settings.production
      - BROKER=kafka://kafka:9092
      - BROKER_CONSUMER=kafka://kafka:9092;kafka://kafka.rogues.caida.org:9392
      - BROKER_PRODUCER=kafka://kafka:9092
      - BROKER_NAME=kafka
      - BROKER_PORT=9092
      - WORKER_ID=1
      - DUMP_DIR=/data/dumps/
      - SLACK_TOKEN=
      - SLACK_CHANNEL=
  doscrawler2:
    container_name: doscrawler2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - doscrawler-data:/data/
    logging:
      driver: "json-file"
      options:
        max-size: "5mb"
        max-file: "10"
    depends_on:
      - kafka
      - zookeeper
    environment:
      - SIMPLE_SETTINGS=doscrawler.settings.production
      - BROKER=kafka://kafka:9092
      - BROKER_CONSUMER=kafka://kafka:9092;kafka://kafka.rogues.caida.org:9392
      - BROKER_PRODUCER=kafka://kafka:9092
      - BROKER_NAME=kafka
      - BROKER_PORT=9092
      - WORKER_ID=2
      - DUMP_DIR=/data/dumps/
      - SLACK_TOKEN=
      - SLACK_CHANNEL=
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    container_name: kafka
    ports:
    - "9092:9092"
    depends_on:
    - zookeeper
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_MESSAGE_MAX_BYTES=2097152
      - KAFKA_NUM_PARTITIONS=4
      - KAFKA_BROKER_ID=1
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"

volumes:
  doscrawler-data:
    driver: local
